spring:
   datasource: 
     url: jdbc:h2:mem:bankdb  
     driverClassName: org.h2.Driver
     username: sa
     password:


   jpa:
     show-sql: true
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: none
       
     properties:
        hibernate:
            cache:
               ehcache: 
                 config: classpath:ehcache.xml
               use_second_level_cache: true
               use_query_cache: true 
               region:
                  factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory 
   h2:
     console:
       enabled: true
       path: /h2-console


   
      
logging:
  level:
    org:
    hibernate:
        type: trace

       
      